### ISSUE TITLE
Create a DM .feature unit_testing library

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#11673]
I'd like it so we have a way to write unit tests faster, without the hassle of dealing with DM code. I want this to be simple to right and in normal english, with the lines matching patterns and being parsed into code.

Not sure if this should be an external program built into the CI, or if it should just be part of DM itself, being part of DM could be handy since then we can just add a button in-game to be able to run these files.

I want:
- The ability to define lines that will get converted into code
- Each test will show as a seperate test on the unit test runner.

Example:
```yaml
pattern:
  match:
    Define (\w+) as new (\w+)
  code:
    var/$1 = allocate($2)
pattern:
  match:
    When (\w+) (\w+) is set to (\w+)
  code:
    $1.$2 = $3
pattern:
  match:
    When human is next to (\w+)
  code:
    var/mob/living/carbon/human/test_mob = new($1.loc)
pattern:
  match:
    (\w+) (\w+) should be (\w+)
  code:
    if ($1.$2 == $3)
      return
    DEFAULT_TEST_FAIL
```

Test file:
```
[code]
/obj/item/assembly/unit_test
	var/pressed = FALSE

/obj/item/assembly/unit_test/pulsed(mob/pulser)
	. = ..()
	pressed = TRUE

Test button click interaction:
Define button as new /obj/machinery/button
Define device as new /obj/item/assembly/unit_test
When button device is set to device
When a human is next to a button
When a human clicks button
Device pressed should be 1
```

I need to consider some other use-cases to see how many unit tests this could easilly create, we want things for:
- ui_act interactions
- Computer interactions
- Weapon hit interactions
- AI/silicons using things
- Check some do_afters
- Check healing and medical items
- If we can, the ability to create rules that interact with a UI and send clicks through clicking on elements with javascript ID (though this is a level above everything else)

Note that this will be for interaction testing and not for writing general tests that should be normal tests. These are expected to be relatively simpler but there will be a greater expectation for people to write these into their PRs.

**Comment by PowerfulBacon** [comment]
If its going to be entirely handled in DM, then the variables will need to be in a store rather than just defined as var/whatever. But in that case, we could have a single DM file defining our procs with the help of some crazy defines:

```
// something like this
ON_MATCH("Define (\w+) as new (\w+)")
  vars.set(match[1], allocate(match[2]))

ON_MATCH("When (\w+) (\w+) is set to (\w+)")
  match[1]:vars[match[2]] = match[3]

etc.
```

Little bit more complicated to write the rules though.

**Comment by PowerfulBacon** [comment]
Another slightly more complicated idea is to have a debug verb that records a test, keeps track of all user inputs and then has the ability to play them back. Some special action buttons are granted to test expected variable states. This would make it easy for people to add automated tests for new content, but makes it harder to do stuff like add custom things that do something when they trigger, for the sake of actually testing expected values

**Comment by PowerfulBacon** [comment]
The actions will be defined in yml:
```yml
patterns:
  - match: Define (\w+) as new (\w+)
    code: |
      var/$1 = allocate($2)
  - match: When (\w+) (\w+) is set to (\w+)
    code: |
      $1.$2 = $3
  - match: When human is next to (\w+)
    code: |
      var/mob/living/carbon/human/test_mob = new($1.loc)
  - match: (\w+) (\w+) should be (\w+)
    code: |
      if ($1.$2 == $3)
        return
      DEFAULT_TEST_FAIL
```

The tests will be defined as .feature files:
```feature
Feature: Button Interaction
  In order to verify the button click interaction with a device
  a mob should click a button and verify that the device attached
  to it recieved a signal

  Background:
    # Inject code necessary for the test to run
    Given the following code is injected:
      """
      /obj/item/assembly/unit_test
        var/pressed = FALSE

      /obj/item/assembly/unit_test/pulsed(mob/pulser)
        . = ..()
        pressed = TRUE
      """

  Scenario: Button click interaction test
    Given button is defined as new /obj/machinery/button
    And device is defined as new /obj/item/assembly/unit_test
    When the button device is set to device
    And a human is next to a button
    And a human clicks the button
    Then device pressed should be 1
```

These files will be compiled into .dm tests by the build process when we are running the unit test configuration and the output will be placed into a directory ignored by git.
